# Form implementation generated from reading ui file 'add_product.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(211, 343)
        self.save_btn = QtWidgets.QPushButton(parent=Dialog)
        self.save_btn.setGeometry(QtCore.QRect(60, 290, 75, 24))
        self.save_btn.setObjectName("save_btn")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 10, 171, 261))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_name = QtWidgets.QLineEdit(parent=self.widget)
        self.line_name.setObjectName("line_name")
        self.verticalLayout.addWidget(self.line_name)
        self.box_type = QtWidgets.QComboBox(parent=self.widget)
        self.box_type.setObjectName("box_type")
        self.verticalLayout.addWidget(self.box_type)
        self.line_article = QtWidgets.QLineEdit(parent=self.widget)
        self.line_article.setObjectName("line_article")
        self.verticalLayout.addWidget(self.line_article)
        self.line_price = QtWidgets.QLineEdit(parent=self.widget)
        self.line_price.setObjectName("line_price")
        self.verticalLayout.addWidget(self.line_price)
        self.box_material = QtWidgets.QComboBox(parent=self.widget)
        self.box_material.setObjectName("box_material")
        self.verticalLayout.addWidget(self.box_material)
        self.box_shop = QtWidgets.QComboBox(parent=self.widget)
        self.box_shop.setObjectName("box_shop")
        self.verticalLayout.addWidget(self.box_shop)
        self.line_time = QtWidgets.QLineEdit(parent=self.widget)
        self.line_time.setObjectName("line_time")
        self.verticalLayout.addWidget(self.line_time)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавить продукт"))
        self.save_btn.setText(_translate("Dialog", "Сохранить"))
        self.line_name.setPlaceholderText(_translate("Dialog", "Название"))
        self.box_type.setPlaceholderText(_translate("Dialog", "Тип"))
        self.line_article.setText(_translate("Dialog", "Артикул"))
        self.line_price.setPlaceholderText(_translate("Dialog", "Мин.цена"))
        self.box_material.setPlaceholderText(_translate("Dialog", "Материал"))
        self.box_shop.setPlaceholderText(_translate("Dialog", "Цех"))
        self.line_time.setPlaceholderText(_translate("Dialog", "Время"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
