# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 761, 431))
        self.tableWidget.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"font-family: Segoe UI")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.open_shop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.open_shop.setGeometry(QtCore.QRect(674, 533, 101, 41))
        self.open_shop.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"font-family: Segoe UI")
        self.open_shop.setObjectName("open_shop")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 540, 581, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_btn = QtWidgets.QPushButton(parent=self.widget)
        self.add_btn.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"font-family: Segoe UI")
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout.addWidget(self.add_btn)
        self.delete_btn = QtWidgets.QPushButton(parent=self.widget)
        self.delete_btn.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"font-family: Segoe UI")
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout.addWidget(self.delete_btn)
        self.edit_btn = QtWidgets.QPushButton(parent=self.widget)
        self.edit_btn.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"font-family: Segoe UI")
        self.edit_btn.setObjectName("edit_btn")
        self.horizontalLayout.addWidget(self.edit_btn)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Мебель"))
        self.open_shop.setText(_translate("MainWindow", "Цеха"))
        self.add_btn.setText(_translate("MainWindow", "Добавить"))
        self.delete_btn.setText(_translate("MainWindow", "Удалить"))
        self.edit_btn.setText(_translate("MainWindow", "Редактировать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())

"""
CREATE TABLE users(
	id INT AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(50),
    password VARCHAR(50)
);

CREATE TABLE type_material(
	id INT AUTO_INCREMENT PRIMARY KEY,
    name_type_material VARCHAR(50)
);

CREATE TABLE materials(
	id INT AUTO_INCREMENT PRIMARY KEY,
    name_material VARCHAR(50)
);

CREATE TABLE type_products(
	id INT AUTO_INCREMENT PRIMARY KEY,
    name_type_products VARCHAR(50)
);

CREATE TABLE shop(
	id INT AUTO_INCREMENT PRIMARY KEY,
    name_shop VARCHAR(50),
    people INT
);

CREATE TABLE products(
	id INT AUTO_INCREMENT PRIMARY KEY,
    name_products VARCHAR(50),
    id_type_products INT,
    article VARCHAR(50),
    min_price DECIMAL(8,2),
    id_type_material INT,
    id_materials INT,
    id_shop INT,
    time_ready INT,
    FOREIGN KEY (id_type_products) REFERENCES type_products(id),
    FOREIGN KEY (id_type_material) REFERENCES type_material(id),
    FOREIGN KEY (id_materials) REFERENCES materials(id),
    FOREIGN KEY (id_shop) REFERENCES shop(id)
);

INSERT INTO users (login, password)
VALUES ('user', 'user123');

INSERT INTO type_material (name_type_material)
VALUES ('Дерево'),
('Металл');

INSERT INTO materials (name_material)
VALUES ('Дуб'),
('Сосна');

INSERT INTO type_products (name_type_products)
VALUES ('Мягкая мебель'),
('Кухонная мебель');

INSERT INTO shop (name_shop, people)
VALUES ('Покрасочный', '45'),
('Столярный', '60');

INSERT INTO products (name_products, id_type_products, article, min_price, id_materials, id_shop, time_ready)
VALUES ('Стол', '2', 'STOL001', '10000.00', '1', '2', '40'),
('Шкаф', '2', 'SHKAF001', '15000.00', '1', '2', '60'),
('Кресло', '1', 'KRESLO001', '8000.00', '2', '1', '30');
"""


