# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 761, 431))
        self.tableWidget.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"font-family: Segoe UI")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.open_shop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.open_shop.setGeometry(QtCore.QRect(674, 533, 101, 41))
        self.open_shop.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"font-family: Segoe UI")
        self.open_shop.setObjectName("open_shop")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 540, 581, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_btn = QtWidgets.QPushButton(parent=self.widget)
        self.add_btn.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"font-family: Segoe UI")
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout.addWidget(self.add_btn)
        self.delete_btn = QtWidgets.QPushButton(parent=self.widget)
        self.delete_btn.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"font-family: Segoe UI")
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout.addWidget(self.delete_btn)
        self.edit_btn = QtWidgets.QPushButton(parent=self.widget)
        self.edit_btn.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"font-family: Segoe UI")
        self.edit_btn.setObjectName("edit_btn")
        self.horizontalLayout.addWidget(self.edit_btn)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Мебель"))
        self.open_shop.setText(_translate("MainWindow", "Цеха"))
        self.add_btn.setText(_translate("MainWindow", "Добавить"))
        self.delete_btn.setText(_translate("MainWindow", "Удалить"))
        self.edit_btn.setText(_translate("MainWindow", "Редактировать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
