# Form implementation generated from reading ui file 'shop_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Shop_window(object):
    def setupUi(self, Shop_window):
        Shop_window.setObjectName("Shop_window")
        Shop_window.resize(566, 469)
        self.tableWidget = QtWidgets.QTableWidget(parent=Shop_window)
        self.tableWidget.setGeometry(QtCore.QRect(20, 30, 521, 301))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.exit_btn = QtWidgets.QPushButton(parent=Shop_window)
        self.exit_btn.setGeometry(QtCore.QRect(460, 380, 81, 51))
        self.exit_btn.setObjectName("exit_btn")
        self.widget = QtWidgets.QWidget(parent=Shop_window)
        self.widget.setGeometry(QtCore.QRect(20, 390, 401, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add2_btn = QtWidgets.QPushButton(parent=self.widget)
        self.add2_btn.setObjectName("add2_btn")
        self.horizontalLayout.addWidget(self.add2_btn)


        self.edit2_btn = QtWidgets.QPushButton(parent=self.widget)
        self.edit2_btn.setObjectName("edit2_btn")
        self.horizontalLayout.addWidget(self.edit2_btn)

        self.retranslateUi(Shop_window)
        QtCore.QMetaObject.connectSlotsByName(Shop_window)

    def retranslateUi(self, Shop_window):
        _translate = QtCore.QCoreApplication.translate
        Shop_window.setWindowTitle(_translate("Shop_window", "Цеха"))
        self.exit_btn.setText(_translate("Shop_window", "Выход"))
        self.add2_btn.setText(_translate("Shop_window", "Добавить"))
        self.edit2_btn.setText(_translate("Shop_window", "Редактировать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Shop_window = QtWidgets.QDialog()
    ui = Ui_Shop_window()
    ui.setupUi(Shop_window)
    Shop_window.show()
    sys.exit(app.exec())
